# Generated by Django 4.2.7 on 2023-12-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_deliver_car_color_alter_deliver_car_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitems',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='main.packages'),
        ),
    ]
