# Generated by Django 4.2.7 on 2023-12-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_options_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='net_profit',
            field=models.IntegerField(default=0),
        ),
    ]
