# Generated by Django 4.2.7 on 2023-12-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sold_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='net_profit',
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_price',
            field=models.IntegerField(default=0, verbose_name='Tan Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name="Tovar haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Tovar nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='Eski narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Narxi'),
        ),
    ]
