# Generated by Django 4.2.7 on 2023-12-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_net_profit_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
