# Generated by Django 4.2.7 on 2023-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_aksiyalar_qoshish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksiyalar_qoshish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
